{
 "title": "Node",
 "description": "Farmalytics sensor and webcam",
 "tags": [ "farmalytics" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "farenheit", "label": "Temperature (Farenheit)" }
   ],
   "targets": [
    {
     "expr": "farmalytics_temperature{source!=\"openweather\"}",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "farmalytics_temperature{source=\"openweather\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 4, "x": 17, "y": 0 } },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "humidity", "label": "Humidity (%)" }
   ],
   "targets": [
    {
     "expr": "farmalytics_humidity{source!=\"openweather\"}",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "farmalytics_humidity{source=\"openweather\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Soil Moisture",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 20 },
   "targets": [
    { "expr": "farmalytics_moisture", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Cam",
   "type": "text",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 27 },
   "content": "<iframe src=\"http://pi-ip:8010\" width=\"100%\" height=\"100%\"></iframe>"
  }
 ]
}