version: "3.7"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      - backend
      - frontend
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    volumes:
      - ./grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    networks:
      - backend
      - frontend
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus