version: "2"

services:
  elk:
    image: sebp/elk
    container_name: elk
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/elasticsearch
    ports:
      - "9200:9200"
      - "5601:5601"
      - "5044:5044"
