version: "2"

services:
  elk:
    container_name: farmalytics-elk
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/elasticsearch
    ports:
      - "9200:9200"
      - "5601:5601"
      - "5044:5044"
