version: "3.7"

services:
  node:
    container_name: farmalytics
    build:
      context: farmalytics
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 666:666
    privileged: true
    env_file:
      - farmalytics.env
    healthcheck:
      test: curl -sS http://127.0.0.1:666 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  motion:
    container_name: motion
    build:
      context: motion
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - /mnt/motion:/var/lib/motion
      - ./motion_config:/etc/motion
    ports:
      - 8080:8080
      - 8081:8081
    devices:
      - /dev/video0:dev/video0
    env_file:
      - farmalytics.env