version: "2"

services:
  farmalytics:
    container_name: farmalytics-node
    build:
      context: farmalytics
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/farmalytics
    privileged: true

  motion:
    container_name: farmalytics-motion
    build:
      context: motion
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - /mnt/motion:/var/lib/motion
    ports:
      - 8080:8080
      - 8081:8081
    devices:
      - /dev/video0:dev/video0