version: "3.7"

services:
  node:
    container_name: farmalytics-node
    build:
      context: farmalytics
      dockerfile: ./Dockerfile
    restart: unless-stopped
    privileged: true
    environment:
      TZ: "America/New_York"

  motion:
    container_name: farmalytics-motion
    build:
      context: motion
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - /mnt/motion:/var/lib/motion
    ports:
      - 8080:8080
      - 8081:8081
    devices:
      - /dev/video0:dev/video0
    environment:
      TZ: "America/New_York"